[2013-09-11 08:58:31] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '/'' in D:\wamp\www\compod\compod\app\storage\views\05a8bd3494fc89d161da39cea1ca012e:23
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-11 09:00:30] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:00:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:00:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:00:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:00:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:01:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:01:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:01:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:01:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:01:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:01:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:02:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:02:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:02:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:02:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:03:18] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:03:18] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:03:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:03:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:06:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:06:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:06:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:06:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:06:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:06:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:07:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 09:07:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 10:43:11] log.ERROR: exception 'ErrorException' with message 'PDO::__construct() [<a href='pdo.--construct'>pdo.--construct</a>]: [2002] A connection attempt failed because the connected party did not properly respond after a period of time, or established connecti (trying to connect via tcp://eu-cdbr-azure-north-a.cloudapp.net:3306)' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'PDO::__construc...', 'D:\wamp\www\com...', 47, Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=eu-c...', 'b58e714ddd9e63', 'fd104d27', Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=eu-c...', Array, Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(115): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2365): Illuminate\Database\DatabaseManager->connection(NULL)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2331): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1436): Illuminate\Database\Eloquent\Model->getConnection()
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1370): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(56): Illuminate\Database\Eloquent\Model->newQuery()
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(275): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#12 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Manager.php(127): call_user_func_array(Array, Array)
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Support\Manager->__call('attempt', Array)
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Auth\AuthManager->attempt(Array)
#16 D:\wamp\www\compod\compod\app\routes.php(28): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#17 D:\wamp\www\compod\compod\app\routes.php(28): Illuminate\Support\Facades\Auth::attempt(Array)
#18 [internal function]: {closure}()
#19 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#25 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#26 {main} [] []
[2013-09-11 10:44:21] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in D:\wamp\www\compod\compod\app\storage\views\05a8bd3494fc89d161da39cea1ca012e:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-11 10:48:20] log.ERROR: exception 'ErrorException' with message 'PDO::__construct() [<a href='pdo.--construct'>pdo.--construct</a>]: [2002] A connection attempt failed because the connected party did not properly respond after a period of time, or established connecti (trying to connect via tcp://eu-cdbr-azure-north-a.cloudapp.net:3306)' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'PDO::__construc...', 'D:\wamp\www\com...', 47, Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=eu-c...', 'b58e714ddd9e63', 'fd104d27', Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=eu-c...', Array, Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(115): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2365): Illuminate\Database\DatabaseManager->connection(NULL)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2331): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1436): Illuminate\Database\Eloquent\Model->getConnection()
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1370): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(56): Illuminate\Database\Eloquent\Model->newQuery()
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(275): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#12 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Manager.php(127): call_user_func_array(Array, Array)
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Support\Manager->__call('attempt', Array)
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Auth\AuthManager->attempt(Array)
#16 D:\wamp\www\compod\compod\app\routes.php(28): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#17 D:\wamp\www\compod\compod\app\routes.php(28): Illuminate\Support\Facades\Auth::attempt(Array)
#18 [internal function]: {closure}()
#19 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#25 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#26 {main} [] []
[2013-09-11 10:50:46] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected T_STRING' in D:\wamp\www\compod\compod\app\storage\views\9ed37656c939add03ff35863e8ef134d:11
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-11 10:50:55] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '{'' in D:\wamp\www\compod\compod\app\storage\views\9ed37656c939add03ff35863e8ef134d:11
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-11 10:53:39] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 10:54:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 10:54:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1439
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:05:44] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1439
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:16:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:16:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:17:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:17:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:18:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:18:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:18:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:19:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:19:47] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:21:05] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:21:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:32:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#5 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#6 {main} [] []
[2013-09-11 11:52:52] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::login()' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1592
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('login', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->login(Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(731): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('login', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->login(Array)
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2545): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('login', Array)
#7 [internal function]: User->login(Array)
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2559): call_user_func_array(Array, Array)
#9 D:\wamp\www\compod\compod\app\routes.php(28): Illuminate\Database\Eloquent\Model::__callStatic('login', Array)
#10 D:\wamp\www\compod\compod\app\routes.php(28): User::login(Array)
#11 [internal function]: {closure}()
#12 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#18 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#19 {main} [] []
[2013-09-11 12:28:10] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Skills' not found' in D:\wamp\www\compod\compod\app\routes.php:63
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-11 13:02:09] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'field list'' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php:330
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(330): PDO->prepare('insert into `po...')
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(520): Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `po...', Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): Illuminate\Database\Connection->run('insert into `po...', Array, Object(Closure))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(288): Illuminate\Database\Connection->statement('insert into `po...', Array)
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1364): Illuminate\Database\Connection->insert('insert into `po...', Array)
#5 D:\wamp\www\compod\compod\app\controllers\PodcastController.php(37): Illuminate\Database\Query\Builder->insert(Array)
#6 [internal function]: PodcastController->createTestPodcasts()
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('createTestPodca...', Array)
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'createTestPodca...', Array)
#10 [internal function]: Illuminate\Routing\{closure}()
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#12 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#17 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#18 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'field list' (SQL: insert into `podcasts` (`name`, `0`) values (?, ?)) (Bindings: array (
  0 => 'FPS',
  1 => 'description\'  => \'If you like cameras stuck in your head while you\'re shooting stuff, than this podcast is for you.',
))' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php:555
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(528): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `po...', Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): Illuminate\Database\Connection->run('insert into `po...', Array, Object(Closure))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(288): Illuminate\Database\Connection->statement('insert into `po...', Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1364): Illuminate\Database\Connection->insert('insert into `po...', Array)
#4 D:\wamp\www\compod\compod\app\controllers\PodcastController.php(37): Illuminate\Database\Query\Builder->insert(Array)
#5 [internal function]: PodcastController->createTestPodcasts()
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('createTestPodca...', Array)
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'createTestPodca...', Array)
#9 [internal function]: Illuminate\Routing\{closure}()
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#12 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#16 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#17 {main} [] []
[2013-09-11 13:07:22] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in D:\wamp\www\compod\compod\app\storage\views\a123145b8ab5b110aef8d4542a26f974:94
Stack trace:
#0 D:\wamp\www\compod\compod\app\storage\views\a123145b8ab5b110aef8d4542a26f974(94): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', 'D:\wamp\www\com...', 94, Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('D:\wamp\www\com...')
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\wamp\www\com...', Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('D:\wamp\www\com...', Array)
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents()
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#6 D:\wamp\www\compod\compod\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(58): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#13 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#14 {main} [] []
[2013-09-11 13:22:46] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array)
#1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('createTestEpiso...', Array)
#2 [internal function]: PodcastController->createTestEpisodes()
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('createTestEpiso...', Array)
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'createTestEpiso...', Array)
#6 [internal function]: Illuminate\Routing\{closure}()
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#13 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#14 {main} [] []
[2013-09-11 13:22:57] log.ERROR: exception 'ReflectionException' with message 'Class EpisodeController does not exist' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Container\Container.php:296
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Container\Container.php(296): ReflectionClass->__construct('EpisodeControll...')
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Container\Container.php(238): Illuminate\Container\Container->build('EpisodeControll...', Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(434): Illuminate\Container\Container->make('EpisodeControll...', Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(983): Illuminate\Foundation\Application->make('EpisodeControll...')
#4 [internal function]: Illuminate\Routing\{closure}()
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#10 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#11 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#12 {main} [] []
[2013-09-11 13:23:18] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'topic' in 'field list'' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php:330
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(330): PDO->prepare('insert into `ep...')
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(520): Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ep...', Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): Illuminate\Database\Connection->run('insert into `ep...', Array, Object(Closure))
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(288): Illuminate\Database\Connection->statement('insert into `ep...', Array)
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1364): Illuminate\Database\Connection->insert('insert into `ep...', Array)
#5 D:\wamp\www\compod\compod\app\controllers\EpisodeController.php(13): Illuminate\Database\Query\Builder->insert(Array)
#6 [internal function]: EpisodeController->createTestEpisodes()
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('createTestEpiso...', Array)
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'createTestEpiso...', Array)
#10 [internal function]: Illuminate\Routing\{closure}()
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#12 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#17 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#18 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'topic' in 'field list' (SQL: insert into `episodes` (`title`, `description`, `topic`, `file`) values (?, ?, ?, ?)) (Bindings: array (
  0 => 'Gaming 101',
  1 => 'How do we define gaming? Why do we game and what do we play?',
  2 => 52,
  3 => 'gaming101.mp3',
))' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php:555
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(528): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `ep...', Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): Illuminate\Database\Connection->run('insert into `ep...', Array, Object(Closure))
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connection.php(288): Illuminate\Database\Connection->statement('insert into `ep...', Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1364): Illuminate\Database\Connection->insert('insert into `ep...', Array)
#4 D:\wamp\www\compod\compod\app\controllers\EpisodeController.php(13): Illuminate\Database\Query\Builder->insert(Array)
#5 [internal function]: EpisodeController->createTestEpisodes()
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('createTestEpiso...', Array)
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'createTestEpiso...', Array)
#9 [internal function]: Illuminate\Routing\{closure}()
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#12 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#16 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#17 {main} [] []
[2013-09-11 14:19:52] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42000] [1226] User 'b58e714ddd9e63' has exceeded the 'max_user_connections' resource (current value: 4)' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=eu-c...', 'b58e714ddd9e63', 'fd104d27', Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=eu-c...', Array, Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(115): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(219): Illuminate\Database\DatabaseManager->connection()
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Database\DatabaseManager->__call('table', Array)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Database\DatabaseManager->table('user_skill')
#8 D:\wamp\www\compod\compod\app\controllers\UserController.php(61): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#9 D:\wamp\www\compod\compod\app\controllers\UserController.php(61): Illuminate\Support\Facades\DB::table('user_skill')
#10 [internal function]: UserController->makeTestSkillOwners()
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#12 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('makeTestSkillOw...', Array)
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'makeTestSkillOw...', Array)
#14 [internal function]: Illuminate\Routing\{closure}()
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#16 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#17 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#21 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#22 {main} [] []
[2013-09-11 14:20:01] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42000] [1226] User 'b58e714ddd9e63' has exceeded the 'max_user_connections' resource (current value: 4)' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=eu-c...', 'b58e714ddd9e63', 'fd104d27', Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=eu-c...', Array, Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(115): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(219): Illuminate\Database\DatabaseManager->connection()
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Database\DatabaseManager->__call('table', Array)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(177): Illuminate\Database\DatabaseManager->table('user_skill')
#8 D:\wamp\www\compod\compod\app\controllers\UserController.php(61): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#9 D:\wamp\www\compod\compod\app\controllers\UserController.php(61): Illuminate\Support\Facades\DB::table('user_skill')
#10 [internal function]: UserController->makeTestSkillOwners()
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#12 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('makeTestSkillOw...', Array)
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'makeTestSkillOw...', Array)
#14 [internal function]: Illuminate\Routing\{closure}()
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#16 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#17 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#21 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#22 {main} [] []
[2013-09-11 14:33:44] log.ERROR: exception 'ErrorException' with message 'Undefined property: stdClass::$id' in D:\wamp\www\compod\compod\app\storage\views\a123145b8ab5b110aef8d4542a26f974:60
Stack trace:
#0 D:\wamp\www\compod\compod\app\storage\views\a123145b8ab5b110aef8d4542a26f974(60): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', 'D:\wamp\www\com...', 60, Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('D:\wamp\www\com...')
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\wamp\www\com...', Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('D:\wamp\www\com...', Array)
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents()
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#6 D:\wamp\www\compod\compod\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(58): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#13 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#14 {main} [] []
[2013-09-11 14:38:57] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42000] [1226] User 'b58e714ddd9e63' has exceeded the 'max_user_connections' resource (current value: 4)' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=eu-c...', 'b58e714ddd9e63', 'fd104d27', Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=eu-c...', Array, Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(115): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2365): Illuminate\Database\DatabaseManager->connection(NULL)
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2331): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1436): Illuminate\Database\Eloquent\Model->getConnection()
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1370): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(42): Illuminate\Database\Eloquent\Model->newQuery()
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(128): Illuminate\Auth\EloquentUserProvider->retrieveById(62)
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(402): Illuminate\Auth\Guard->user()
#12 [internal function]: Illuminate\Auth\Guard->logout()
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Manager.php(127): call_user_func_array(Array, Array)
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(174): Illuminate\Support\Manager->__call('logout', Array)
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(174): Illuminate\Auth\AuthManager->logout()
#16 D:\wamp\www\compod\compod\app\routes.php(50): Illuminate\Support\Facades\Facade::__callStatic('logout', Array)
#17 D:\wamp\www\compod\compod\app\routes.php(50): Illuminate\Support\Facades\Auth::logout()
#18 [internal function]: {closure}()
#19 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#25 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#26 {main} [] []
[2013-09-11 14:39:11] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42000] [1226] User 'b58e714ddd9e63' has exceeded the 'max_user_connections' resource (current value: 4)' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=eu-c...', 'b58e714ddd9e63', 'fd104d27', Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=eu-c...', Array, Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(115): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2365): Illuminate\Database\DatabaseManager->connection(NULL)
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2331): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1436): Illuminate\Database\Eloquent\Model->getConnection()
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1370): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(42): Illuminate\Database\Eloquent\Model->newQuery()
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(128): Illuminate\Auth\EloquentUserProvider->retrieveById(62)
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(402): Illuminate\Auth\Guard->user()
#12 [internal function]: Illuminate\Auth\Guard->logout()
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Manager.php(127): call_user_func_array(Array, Array)
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(174): Illuminate\Support\Manager->__call('logout', Array)
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(174): Illuminate\Auth\AuthManager->logout()
#16 D:\wamp\www\compod\compod\app\routes.php(50): Illuminate\Support\Facades\Facade::__callStatic('logout', Array)
#17 D:\wamp\www\compod\compod\app\routes.php(50): Illuminate\Support\Facades\Auth::logout()
#18 [internal function]: {closure}()
#19 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#25 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#26 {main} [] []
[2013-09-11 14:48:09] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42000] [1226] User 'b58e714ddd9e63' has exceeded the 'max_user_connections' resource (current value: 4)' in D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=eu-c...', 'b58e714ddd9e63', 'fd104d27', Array)
#1 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=eu-c...', Array, Array)
#2 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(115): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2365): Illuminate\Database\DatabaseManager->connection(NULL)
#6 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2331): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#7 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1436): Illuminate\Database\Eloquent\Model->getConnection()
#8 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1370): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#9 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(42): Illuminate\Database\Eloquent\Model->newQuery()
#10 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(128): Illuminate\Auth\EloquentUserProvider->retrieveById(52)
#11 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(99): Illuminate\Auth\Guard->user()
#12 [internal function]: Illuminate\Auth\Guard->guest()
#13 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Manager.php(127): call_user_func_array(Array, Array)
#14 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(174): Illuminate\Support\Manager->__call('guest', Array)
#15 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(174): Illuminate\Auth\AuthManager->guest()
#16 D:\wamp\www\compod\compod\app\filters.php(65): Illuminate\Support\Facades\Facade::__callStatic('guest', Array)
#17 D:\wamp\www\compod\compod\app\filters.php(65): Illuminate\Support\Facades\Auth::guest()
#18 [internal function]: {closure}(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#19 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(159): call_user_func_array(Object(Closure), Array)
#20 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(100): Illuminate\Routing\Route->callFilter('auth', Object(Illuminate\Http\Request))
#21 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(43): Illuminate\Routing\Route->callBeforeFilters(Object(Illuminate\Http\Request))
#22 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 D:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 D:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#26 D:\wamp\www\compod\compod\server.php(19): require_once('D:\wamp\www\com...')
#27 {main} [] []
[2013-09-11 18:09:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '<'' in E:\wamp\www\compod\compod\app\storage\views\f245179e46c4bc1c765ef59f4e55db8e:49
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-11 18:31:21] log.ERROR: exception 'ErrorException' with message 'Undefined variable: episode' in E:\wamp\www\compod\compod\app\storage\views\9e848fe3af9b9ff48173a966d96762bb:8
Stack trace:
#0 E:\wamp\www\compod\compod\app\storage\views\9e848fe3af9b9ff48173a966d96762bb(8): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'E:\wamp\www\com...', 8, Array)
#1 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('E:\wamp\www\com...')
#2 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('E:\wamp\www\com...', Array)
#3 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('E:\wamp\www\com...', Array)
#4 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents()
#5 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View->render()
#6 E:\wamp\www\compod\compod\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Route.php(58): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 E:\wamp\www\compod\compod\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 E:\wamp\www\compod\compod\public\index.php(49): Illuminate\Foundation\Application->run()
#13 E:\wamp\www\compod\compod\server.php(19): require_once('E:\wamp\www\com...')
#14 {main} [] []
